LANGUAGE = 'chinese'
TERM = '资本存入期限（年）: '
INITIAL_CAPITAL = '种子资本 ($): '
PERCENTAGE = '利率 (%/月): '
INVESTMENT = '投资注入 ($/月): '
INPUT_ERROR = '请正确输入数据: '
YEAR = '年'
LINE1 = '|   月  |     投资基础   |  每月利息金额  |      资本     |'
BORDER = '-' * 57